Addmission/urls.py
from django.urls import path
from . views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
      path('', home, name='home'),
      path('contact', contact, name='contact'),
      path('about', about, name='about'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = 'Addmission'

Hospital/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('Addmission.urls')),
]

Addmission/models.py
from django.db import models

# Create your models here.

Addmission/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def home(request):
      # return HttpResponse("Hello from views")
      context = {"title":"HomePage"}
      return render(request, 'Addmission/reports/home.html', context)

def contact(request):
      # return HttpResponse("Hello from views")
      context = {"title":"ContactPage"}
      return render(request, 'Addmission/reports/contact.html', context)

def about(request):
      context = {"title":"AboutPage"}
      return render(request, 'Addmission/reports/about.html', context)

Addmission/templates/Addmission/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{title}}</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
      
      {% block style %}{% endblock %}

      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
      
</head>
<body>
      {% block header %}
            {% include './header.html' %}
      {% endblock %}
      <div class="container">
            <div class="row">
        
                  <div class="col-sm">

                        {% block sideNav %}
                        {% include './side.html' %}
                        {% endblock %}
                  </div>
                  <div class="col-lg">

                        {% block content %}
                              This is content
                        {% endblock %}

                        <br><br><br><br>

                        {% block footer %}
                              {% include './footer.html' with date="23 Nov 2022" var=1234%}
                        {% endblock %}
                  </div>
            </div>
      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

Addmission/templates/Addmission/layout/footer.html
{% load static %}
<div class="card">
      <div class="card-header">
        Footer Quote
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p>A well-known quote, contained in a blockquote element.</p>
          <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
        </blockquote>
        <p>{{date}}</p>
        <p>{{var}}</p>
      </div>
    </div>

Addmission/templates/Addmission/layout/header.html
<nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'Addmission:home' %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'Addmission:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Addmission:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Addmission:contact' %}">Contact</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

Addmission/templates/Addmission/layout/side.html
<ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Addmission:home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Addmission:about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Addmission:contact' %}">Contact</a>
      </li>
    </ul>

Addmission/templates/Addmission/reports/about.html
{% extends '../layout/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- <title>Document</title> -->
      {%block style%}
      <link rel="stylesheet" href="{% static 'Addmission/css/about.css' %}">
      {% endblock %}
</head>
<body>
      {% block content %}
            <h1>This is About Page</h1>
      {% endblock %}
      
</body>
</html>

Addmission/templates/Addmission/reports/contact.html
{% extends '../layout/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- <title>Document</title> -->
      {%block style%}
      <link rel="stylesheet" href="{% static 'Addmission/css/contact.css' %}">
      {% endblock %}
</head>
<body>
      {% block content %}
            <h1>This is Content Page</h1>
      {% endblock %}
      
</body>
</html>

Addmission/templates/Addmission/reports/home.html
{% extends '../layout/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- <title>Document</title> -->
      {%block style%}
      <link rel="stylesheet" href="{% static 'Addmission/css/home.css' %}">
      {% endblock %}
</head>
<body>

      {% block content %}
      <h1>Hello to the HomePage</h1>
      {% endblock %}
      <!-- <img src= "{% static '2at0138.jpg' %}" alt=""> -->
</body>
</html>